export const HANDLE_USERNAME = "HANDLE_USERNAME";
export const HANDLE_PASSWORD = "HANDLE_PASSWORD";
export const HANDLE_FULLNAME = "HANDLE_FULLNAME";
export const REQUEST_SIGNUP = "REQUEST_SIGNUP";
export const RECEIVE_SIGNUP = "RECEIVE_SIGNUP";
