export const HANDLE_USERNAME = "HANDLE_USERNAME";
export const HANDLE_PASSWORD = "HANDLE_PASSWORD";
export const HANDLE_FULLNAME = "HANDLE_FULLNAME";

export const UPDATE_STATUS = "UPDATE_STATUS";

export const LINK_LOGIN = "LINK_LOGIN";
export const LINK_SIGNUP = "LINK_SIGNUP";

export const REQUEST_SIGNUP = "REQUEST_SIGNUP";
export const RECEIVE_SIGNUP = "RECEIVE_SIGNUP";

export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const RECEIVE_TOKEN = "RECEIVE_TOKEN";
